// AUTO-GENERATED from hospital_schedule_part_2.xlsx — the real roster + schedule.
export const HOSPITAL_TODAY =
  "Saturday 20 June 2026, 18:30 — deciding cover just before tonight's night shift.";

export const SHIFT_REF =
  "Shift codes: D = Day 07:00-19:00 (12h); N = Night 19:00-07:00 (12h); O = Off. 'Max Hrs/Week' is the cap on scheduled hours; 'next7d' = hours already scheduled in the next 7 days.";

// One line per staff member: ID | Name | Role | Dept | certs | Contract | max | pref | OT | Status | Fri | Sat(today) | Sun | next7d | (notes)
export const STAFF_DATA = `HOSP-1001 | Isla Nguyen | Registered Nurse | Cardiology | certs:BLS, ACLS | Full-time | max:48 | pref:Day | OT:No | Active | Fri=D | Sat=D | Sun=O | next7d=36 | (Open to last-minute cover)
HOSP-1002 | Tariq Bianchi | Certified Nursing Assistant | General Medicine | certs:BLS | Full-time | max:48 | pref:Flexible | OT:No | Active | Fri=O | Sat=N | Sun=O | next7d=36 | (Commutes far, dislikes back-to-backs)
HOSP-1003 | Hannah Reyes | Registered Nurse | Maternity | certs:BLS, NRP | Full-time | max:48 | pref:Flexible | OT:Yes | Active | Fri=O | Sat=O | Sun=D | next7d=36 | (Has young children, prefers day shifts)
HOSP-1004 | Hassan Novak | Certified Nursing Assistant | Emergency | certs:BLS | Full-time | max:48 | pref:Flexible | OT:Yes | Active | Fri=O | Sat=N | Sun=N | next7d=36 | (Calm under pressure in codes)
HOSP-1005 | Ethan Wagner | Physician | Surgery | certs:BLS, ACLS | Per-diem | max:36 | pref:Flexible | OT:No | Active | Fri=O | Sat=D | Sun=O | next7d=36 | (Commutes far, dislikes back-to-backs)
HOSP-1006 | Hannah Kim | Registered Nurse | Oncology | certs:BLS, OCN | Full-time | max:48 | pref:Flexible | OT:No | Active | Fri=D | Sat=O | Sun=O | next7d=36 | (Working toward charge-nurse role)
HOSP-1007 | Hannah Lindgren | Registered Nurse | Maternity | certs:BLS, NRP | Per-diem | max:36 | pref:Night | OT:Yes | Active | Fri=O | Sat=N | Sun=O | next7d=48 | (Senior staff, mentors new grads)
HOSP-1008 | Sara Weber | Registered Nurse | Cardiology | certs:BLS, ACLS | Per-diem | max:36 | pref:Night | OT:No | Active | Fri=O | Sat=O | Sun=O | next7d=24 | (Union rep, watches hours closely)
HOSP-1009 | Nora Novak | Registered Nurse | Pediatrics | certs:BLS, PALS | Full-time | max:48 | pref:Day | OT:No | Active | Fri=D | Sat=O | Sun=D | next7d=36 | (Prefers predictable schedules)
HOSP-1010 | Caleb Marino | Certified Nursing Assistant | ICU | certs:BLS | Per-diem | max:36 | pref:Day | OT:Yes | Active | Fri=D | Sat=D | Sun=D | next7d=36 | (New grad, still onboarding)
HOSP-1011 | Reza Novak | Physician | General Medicine | certs:BLS, ACLS | Full-time | max:48 | pref:Flexible | OT:No | Active | Fri=D | Sat=O | Sun=O | next7d=24 | (Avoids overtime when possible)
HOSP-1012 | Isla Petrov | Registered Nurse | Maternity | certs:BLS, NRP | Full-time | max:48 | pref:Flexible | OT:No | On Leave | Fri=O | Sat=O | Sun=O | next7d=0 | (Working toward charge-nurse role)
HOSP-1013 | Dunia Esposito | Registered Nurse | Surgery | certs:BLS, ACLS | Part-time | max:30 | pref:Night | OT:No | Active | Fri=O | Sat=N | Sun=O | next7d=48 | (Reliable, frequently picks up extra shifts)
HOSP-1014 | Sofia Müller | Physician | Oncology | certs:BLS, ACLS | Part-time | max:30 | pref:Day | OT:Yes | Active | Fri=O | Sat=D | Sun=O | next7d=12 | (New grad, still onboarding)
HOSP-1015 | Emma Holm | Physician | General Medicine | certs:BLS, ACLS | Full-time | max:48 | pref:Night | OT:Yes | Active | Fri=O | Sat=O | Sun=N | next7d=36 | (Open to last-minute cover)
HOSP-1016 | Niko Weber | Registered Nurse | Oncology | certs:BLS, OCN | Full-time | max:48 | pref:Day | OT:Yes | Active | Fri=D | Sat=D | Sun=D | next7d=48 | (Quiet, dependable, rarely calls out)
HOSP-1017 | Aisha Hernandez | Registered Nurse | Emergency | certs:BLS, ACLS, TNCC | Per-diem | max:36 | pref:Flexible | OT:Yes | Active | Fri=O | Sat=D | Sun=N | next7d=48 | (Union rep, watches hours closely)
HOSP-1018 | Samir Vasquez | Radiologic Technologist | Radiology | certs:ARRT | Full-time | max:48 | pref:Day | OT:Yes | Active | Fri=O | Sat=O | Sun=D | next7d=48 | (Calm under pressure in codes)
HOSP-1019 | Zara Dlamini | Registered Nurse | ICU | certs:BLS, ACLS | Part-time | max:30 | pref:Flexible | OT:Yes | Active | Fri=O | Sat=O | Sun=O | next7d=12 | (Quiet, dependable, rarely calls out)
HOSP-1020 | Marco Costa | Radiologic Technologist | Radiology | certs:ARRT | Per-diem | max:36 | pref:Night | OT:No | Active | Fri=N | Sat=O | Sun=N | next7d=36 | (Senior staff, mentors new grads)
HOSP-1021 | Mateo Holm | Registered Nurse | Surgery | certs:BLS, ACLS | Full-time | max:48 | pref:Day | OT:Yes | Active | Fri=D | Sat=D | Sun=D | next7d=48 | (Prefers predictable schedules)
HOSP-1022 | Greta Petrov | Certified Nursing Assistant | Maternity | certs:BLS | Part-time | max:30 | pref:Flexible | OT:No | Active | Fri=D | Sat=O | Sun=O | next7d=24 | (Part-time by choice, studying part-time)
HOSP-1023 | Nina Sørensen | Registered Nurse | General Medicine | certs:BLS | Full-time | max:48 | pref:Day | OT:Yes | Active | Fri=O | Sat=O | Sun=O | next7d=48 | (Cross-trained on two units)
HOSP-1024 | Olivia Dubois | Certified Nursing Assistant | ICU | certs:BLS | Part-time | max:30 | pref:Day | OT:Yes | Active | Fri=O | Sat=O | Sun=O | next7d=24 | (Float-pool veteran, flexible across units)
HOSP-1025 | Emil Kowalski | Certified Nursing Assistant | Maternity | certs:BLS | Full-time | max:48 | pref:Day | OT:Yes | Active | Fri=D | Sat=D | Sun=D | next7d=48 | (Per-diem, very flexible)
HOSP-1026 | Layla Wagner | Registered Nurse | Cardiology | certs:BLS, ACLS | Per-diem | max:36 | pref:Flexible | OT:Yes | Active | Fri=O | Sat=D | Sun=O | next7d=48 | (Has young children, prefers day shifts)
HOSP-1027 | Dunia Novak | Nurse Practitioner | Pediatrics | certs:BLS, PALS | Per-diem | max:36 | pref:Flexible | OT:Yes | Active | Fri=O | Sat=O | Sun=O | next7d=12 | (Quiet, dependable, rarely calls out)
HOSP-1028 | Liam Wagner | Registered Nurse | General Medicine | certs:BLS | Part-time | max:30 | pref:Flexible | OT:Yes | Active | Fri=O | Sat=O | Sun=O | next7d=12 | (Has young children, prefers day shifts)
HOSP-1029 | Freya Petrov | Pharmacist | Pharmacy | certs:PharmD | Full-time | max:48 | pref:Night | OT:No | Active | Fri=O | Sat=N | Sun=N | next7d=60 | (Avoids overtime when possible)
HOSP-1030 | Mateo Janssen | Physician | Maternity | certs:BLS, ACLS | Full-time | max:48 | pref:Day | OT:Yes | On Leave | Fri=O | Sat=O | Sun=O | next7d=0 | (Working toward charge-nurse role)
HOSP-1031 | Otto Okafor | Registered Nurse | ICU | certs:BLS, ACLS | Per-diem | max:36 | pref:Flexible | OT:Yes | Active | Fri=O | Sat=O | Sun=N | next7d=24 | (Quiet, dependable, rarely calls out)
HOSP-1032 | Ethan Schmidt | Nurse Practitioner | Oncology | certs:BLS, OCN | Part-time | max:30 | pref:Flexible | OT:No | Active | Fri=N | Sat=O | Sun=O | next7d=12 | (Float-pool veteran, flexible across units)
HOSP-1033 | Otto Romano | Pharmacy Technician | Pharmacy | certs:CPhT | Per-diem | max:36 | pref:Day | OT:Yes | Active | Fri=D | Sat=O | Sun=O | next7d=24 | (Working toward charge-nurse role)
HOSP-1034 | Elena Sørensen | Physician | Oncology | certs:BLS, ACLS | Full-time | max:48 | pref:Night | OT:No | Active | Fri=O | Sat=O | Sun=N | next7d=48 | (Working toward charge-nurse role)
HOSP-1035 | Lucia Rossi | Radiologic Technologist | Radiology | certs:ARRT | Part-time | max:30 | pref:Night | OT:Yes | Active | Fri=N | Sat=O | Sun=O | next7d=24 | (Float-pool veteran, flexible across units)
HOSP-1036 | Bruno Ivanov | Physician | Cardiology | certs:BLS, ACLS | Per-diem | max:36 | pref:Day | OT:No | Active | Fri=D | Sat=O | Sun=O | next7d=24 | (Quiet, dependable, rarely calls out)
HOSP-1037 | Jonas Dubois | Pharmacy Technician | Pharmacy | certs:CPhT | Full-time | max:48 | pref:Day | OT:Yes | Active | Fri=D | Sat=D | Sun=O | next7d=24 | (Per-diem, very flexible)
HOSP-1038 | Isla Adeyemi | Pharmacist | Pharmacy | certs:PharmD | Full-time | max:48 | pref:Night | OT:Yes | Active | Fri=O | Sat=N | Sun=N | next7d=48 | (Part-time by choice, studying part-time)
HOSP-1039 | Ines Khan | Certified Nursing Assistant | Oncology | certs:BLS | Full-time | max:48 | pref:Flexible | OT:Yes | Active | Fri=N | Sat=O | Sun=D | next7d=24 | (Per-diem, very flexible)
HOSP-1040 | Wren Silva | Registered Nurse | Surgery | certs:BLS, ACLS | Per-diem | max:36 | pref:Night | OT:No | Active | Fri=O | Sat=O | Sun=O | next7d=48 | (Recently returned from parental leave)
HOSP-1041 | Amara Petrov | Registered Nurse | Surgery | certs:BLS, ACLS | Full-time | max:48 | pref:Night | OT:Yes | Active | Fri=N | Sat=N | Sun=O | next7d=36 | (Part-time by choice, studying part-time)
HOSP-1042 | Olivia Petrov | Certified Nursing Assistant | General Medicine | certs:BLS | Full-time | max:48 | pref:Day | OT:No | Active | Fri=O | Sat=D | Sun=O | next7d=36 | (Recently returned from parental leave)
HOSP-1043 | Nora Nguyen | Registered Nurse | Emergency | certs:BLS, ACLS, TNCC | Full-time | max:48 | pref:Flexible | OT:Yes | Active | Fri=O | Sat=O | Sun=O | next7d=36 | (Part-time by choice, studying part-time)
HOSP-1044 | Pavel Weber | Registered Nurse | Surgery | certs:BLS, ACLS | Part-time | max:30 | pref:Flexible | OT:No | Active | Fri=D | Sat=D | Sun=O | next7d=36 | (Open to last-minute cover)
HOSP-1045 | Malik Patel | Registered Nurse | General Medicine | certs:BLS | Part-time | max:30 | pref:Night | OT:No | Active | Fri=O | Sat=N | Sun=O | next7d=36 | (Quiet, dependable, rarely calls out)
HOSP-1046 | Lara Kovač | Registered Nurse | General Medicine | certs:BLS | Per-diem | max:36 | pref:Night | OT:Yes | Active | Fri=O | Sat=N | Sun=N | next7d=48 | (Commutes far, dislikes back-to-backs)
HOSP-1047 | Ravi Antov | Registered Nurse | General Medicine | certs:BLS | Full-time | max:48 | pref:Night | OT:No | Active | Fri=N | Sat=N | Sun=N | next7d=36 | (Per-diem, very flexible)
HOSP-1048 | Finn Larsson | Registered Nurse | Surgery | certs:BLS, ACLS | Full-time | max:48 | pref:Day | OT:Yes | Active | Fri=D | Sat=D | Sun=D | next7d=48 | (Commutes far, dislikes back-to-backs)
HOSP-1049 | Aaron Adeyemi | Pharmacy Technician | Pharmacy | certs:CPhT | Full-time | max:48 | pref:Flexible | OT:No | Active | Fri=O | Sat=O | Sun=D | next7d=36 | (Calm under pressure in codes)
HOSP-1050 | Aaron Park | Physician | General Medicine | certs:BLS, ACLS | Per-diem | max:36 | pref:Night | OT:Yes | Active | Fri=O | Sat=N | Sun=O | next7d=24 | (Prefers predictable schedules)
HOSP-1051 | Kai Lindgren | Respiratory Therapist | Pediatrics | certs:BLS, ACLS, RRT | Full-time | max:48 | pref:Flexible | OT:No | Active | Fri=N | Sat=O | Sun=D | next7d=48 | (New grad, still onboarding)
HOSP-1052 | Malik Dubois | Registered Nurse | Emergency | certs:BLS, ACLS, TNCC | Full-time | max:48 | pref:Night | OT:Yes | Active | Fri=N | Sat=N | Sun=O | next7d=24 | (Avoids overtime when possible)
HOSP-1053 | Anya Kowalski | Radiologic Technologist | Radiology | certs:ARRT | Full-time | max:48 | pref:Flexible | OT:Yes | Active | Fri=N | Sat=O | Sun=D | next7d=24 | (Senior staff, mentors new grads)
HOSP-1054 | Sam Nguyen | Pharmacist | Pharmacy | certs:PharmD | Full-time | max:48 | pref:Night | OT:No | Active | Fri=N | Sat=O | Sun=N | next7d=48 | (Avoids overtime when possible)
HOSP-1055 | Hassan Esposito | Physician | ICU | certs:BLS, ACLS | Full-time | max:48 | pref:Day | OT:No | On Leave | Fri=O | Sat=O | Sun=O | next7d=0 | (Prefers predictable schedules)
HOSP-1056 | Omar Bakker | Registered Nurse | Surgery | certs:BLS, ACLS | Part-time | max:30 | pref:Flexible | OT:No | Active | Fri=N | Sat=O | Sun=O | next7d=12 | (Senior staff, mentors new grads)
HOSP-1057 | Oskar Hernandez | Certified Nursing Assistant | General Medicine | certs:BLS | Full-time | max:48 | pref:Night | OT:Yes | Active | Fri=O | Sat=O | Sun=N | next7d=36 | (Calm under pressure in codes)
HOSP-1058 | Diego Bauer | Certified Nursing Assistant | Pediatrics | certs:BLS | Per-diem | max:36 | pref:Day | OT:No | Active | Fri=O | Sat=D | Sun=O | next7d=48 | (Union rep, watches hours closely)
HOSP-1059 | Felix Haddad | Registered Nurse | ICU | certs:BLS, ACLS | Full-time | max:48 | pref:Flexible | OT:No | Active | Fri=O | Sat=N | Sun=O | next7d=36 | (Per-diem, very flexible)
HOSP-1060 | Marco Marino | Registered Nurse | Surgery | certs:BLS, ACLS | Full-time | max:48 | pref:Day | OT:No | Active | Fri=D | Sat=O | Sun=D | next7d=48 | (Quiet, dependable, rarely calls out)
HOSP-1061 | Olivia Haddad | Registered Nurse | Maternity | certs:BLS, NRP | Part-time | max:30 | pref:Night | OT:No | Active | Fri=N | Sat=N | Sun=N | next7d=36 | (Reliable, frequently picks up extra shifts)
HOSP-1062 | Bruno Reyes | Registered Nurse | Surgery | certs:BLS, ACLS | Full-time | max:48 | pref:Night | OT:Yes | Active | Fri=N | Sat=N | Sun=N | next7d=48 | (Quiet, dependable, rarely calls out)
HOSP-1063 | Freya Schmidt | Registered Nurse | Cardiology | certs:BLS, ACLS | Part-time | max:30 | pref:Day | OT:No | On Leave | Fri=O | Sat=O | Sun=O | next7d=0 | (Working toward charge-nurse role)
HOSP-1064 | Ravi Kovač | Pharmacy Technician | Pharmacy | certs:CPhT | Full-time | max:48 | pref:Day | OT:Yes | Active | Fri=O | Sat=O | Sun=D | next7d=24 | (Float-pool veteran, flexible across units)
HOSP-1065 | Liam Lefebvre | Registered Nurse | General Medicine | certs:BLS | Full-time | max:48 | pref:Day | OT:Yes | On Leave | Fri=O | Sat=O | Sun=O | next7d=0 | (Union rep, watches hours closely)
HOSP-1066 | Samir Petrov | Radiologic Technologist | Radiology | certs:ARRT | Full-time | max:48 | pref:Flexible | OT:Yes | Active | Fri=O | Sat=D | Sun=O | next7d=24 | (Has young children, prefers day shifts)
HOSP-1067 | Aila Hernandez | Pharmacy Technician | Pharmacy | certs:CPhT | Full-time | max:48 | pref:Day | OT:No | Active | Fri=O | Sat=O | Sun=O | next7d=36 | (Float-pool veteran, flexible across units)
HOSP-1068 | Emil Bianchi | Registered Nurse | General Medicine | certs:BLS | Per-diem | max:36 | pref:Day | OT:No | Active | Fri=O | Sat=D | Sun=D | next7d=48 | (Senior staff, mentors new grads)
HOSP-1069 | Chloe Janssen | Registered Nurse | Surgery | certs:BLS, ACLS | Full-time | max:48 | pref:Day | OT:No | Active | Fri=O | Sat=D | Sun=O | next7d=36 | (Open to last-minute cover)
HOSP-1070 | Theo Rossi | Registered Nurse | Surgery | certs:BLS, ACLS | Full-time | max:48 | pref:Flexible | OT:Yes | Active | Fri=N | Sat=O | Sun=O | next7d=24 | (Avoids overtime when possible)
HOSP-1071 | Yara Müller | Registered Nurse | General Medicine | certs:BLS | Full-time | max:48 | pref:Day | OT:Yes | Active | Fri=O | Sat=D | Sun=O | next7d=36 | (Recently returned from parental leave)
HOSP-1072 | Selin Müller | Radiologic Technologist | Radiology | certs:ARRT | Part-time | max:30 | pref:Flexible | OT:Yes | Active | Fri=O | Sat=N | Sun=O | next7d=48 | (New grad, still onboarding)
HOSP-1073 | Felix Esposito | Registered Nurse | Cardiology | certs:BLS, ACLS | Full-time | max:48 | pref:Night | OT:No | Active | Fri=O | Sat=O | Sun=N | next7d=36 | (Reliable, frequently picks up extra shifts)
HOSP-1074 | Samir Rossi | Registered Nurse | Pediatrics | certs:BLS, PALS | Part-time | max:30 | pref:Flexible | OT:Yes | Active | Fri=O | Sat=N | Sun=O | next7d=36 | (Union rep, watches hours closely)
HOSP-1075 | Carmen Ivanov | Certified Nursing Assistant | Oncology | certs:BLS | Per-diem | max:36 | pref:Day | OT:No | Active | Fri=O | Sat=O | Sun=O | next7d=48 | (Prefers predictable schedules)
HOSP-1076 | Greta Kowalski | Registered Nurse | Oncology | certs:BLS, OCN | Full-time | max:48 | pref:Flexible | OT:No | Active | Fri=O | Sat=D | Sun=N | next7d=36 | (Reliable, frequently picks up extra shifts)
HOSP-1077 | Malik Romano | Registered Nurse | Emergency | certs:BLS, ACLS, TNCC | Full-time | max:48 | pref:Flexible | OT:No | Active | Fri=D | Sat=O | Sun=D | next7d=48 | (Part-time by choice, studying part-time)
HOSP-1078 | Lena Sato | Radiologic Technologist | Radiology | certs:ARRT | Per-diem | max:36 | pref:Night | OT:Yes | Active | Fri=O | Sat=O | Sun=O | next7d=24 | (Quiet, dependable, rarely calls out)
HOSP-1079 | Mateo Bianchi | Registered Nurse | ICU | certs:BLS, ACLS | Full-time | max:48 | pref:Flexible | OT:Yes | Active | Fri=O | Sat=O | Sun=O | next7d=24 | (Cross-trained on two units)
HOSP-1080 | Janek Abebe | Registered Nurse | Surgery | certs:BLS, ACLS | Full-time | max:48 | pref:Day | OT:No | Active | Fri=O | Sat=O | Sun=O | next7d=12 | (Night-owl, happy on nights)
HOSP-1081 | Aaron Ivanov | Registered Nurse | General Medicine | certs:BLS | Full-time | max:48 | pref:Flexible | OT:No | Active | Fri=N | Sat=O | Sun=N | next7d=48 | (Union rep, watches hours closely)
HOSP-1082 | Mei Abebe | Registered Nurse | Oncology | certs:BLS, OCN | Part-time | max:30 | pref:Day | OT:No | Active | Fri=D | Sat=O | Sun=D | next7d=24 | (Float-pool veteran, flexible across units)
HOSP-1083 | Carmen Rossi | Certified Nursing Assistant | Oncology | certs:BLS | Part-time | max:30 | pref:Flexible | OT:Yes | Active | Fri=D | Sat=O | Sun=O | next7d=36 | (Night-owl, happy on nights)
HOSP-1084 | Dunia Bakker | Physician | Oncology | certs:BLS, ACLS | Per-diem | max:36 | pref:Night | OT:Yes | Active | Fri=O | Sat=O | Sun=O | next7d=24 | (Night-owl, happy on nights)
HOSP-1085 | Omar Abebe | Registered Nurse | Cardiology | certs:BLS, ACLS | Part-time | max:30 | pref:Night | OT:No | Active | Fri=N | Sat=N | Sun=N | next7d=36 | (Quiet, dependable, rarely calls out)
HOSP-1086 | Tomas Rossi | Pharmacist | Pharmacy | certs:PharmD | Part-time | max:30 | pref:Flexible | OT:No | Active | Fri=O | Sat=O | Sun=O | next7d=36 | (Open to last-minute cover)
HOSP-1087 | Selin Kovač | Nurse Practitioner | Cardiology | certs:BLS, ACLS | Full-time | max:48 | pref:Flexible | OT:Yes | Active | Fri=N | Sat=O | Sun=D | next7d=36 | (Night-owl, happy on nights)
HOSP-1088 | Bianca Dlamini | Registered Nurse | Pediatrics | certs:BLS, PALS | Full-time | max:48 | pref:Flexible | OT:No | Active | Fri=O | Sat=O | Sun=O | next7d=12 | (Night-owl, happy on nights)
HOSP-1089 | Greta Novak | Nurse Practitioner | Emergency | certs:BLS, ACLS, TNCC | Full-time | max:48 | pref:Day | OT:Yes | Active | Fri=O | Sat=O | Sun=O | next7d=36 | (Calm under pressure in codes)
HOSP-1090 | Anya Lindgren | Registered Nurse | Cardiology | certs:BLS, ACLS | Full-time | max:48 | pref:Night | OT:Yes | Active | Fri=O | Sat=O | Sun=O | next7d=0 | (Recently returned from parental leave)
HOSP-1091 | Hana Costa | Charge Nurse | Emergency | certs:BLS, ACLS, TNCC | Part-time | max:30 | pref:Flexible | OT:Yes | Active | Fri=O | Sat=O | Sun=N | next7d=36 | (Union rep, watches hours closely)
HOSP-1092 | Hassan Fernández | Surgeon | Surgery | certs:BLS, ACLS, ATLS | Part-time | max:30 | pref:Night | OT:No | Active | Fri=O | Sat=N | Sun=O | next7d=36 | (Night-owl, happy on nights)
HOSP-1093 | Niko Sato | Charge Nurse | Emergency | certs:BLS, ACLS, TNCC | Part-time | max:30 | pref:Day | OT:Yes | Active | Fri=O | Sat=D | Sun=D | next7d=48 | (Working toward charge-nurse role)
HOSP-1094 | Nadia Hoffmann | Nurse Practitioner | General Medicine | certs:BLS | Part-time | max:30 | pref:Day | OT:No | Active | Fri=O | Sat=D | Sun=D | next7d=48 | (Recently returned from parental leave)
HOSP-1095 | Isla Lindgren | Registered Nurse | ICU | certs:BLS, ACLS | Per-diem | max:36 | pref:Flexible | OT:No | Active | Fri=O | Sat=O | Sun=O | next7d=0 | (Quiet, dependable, rarely calls out)
HOSP-1096 | Liam Novak | Registered Nurse | General Medicine | certs:BLS | Full-time | max:48 | pref:Flexible | OT:Yes | Active | Fri=O | Sat=O | Sun=D | next7d=36 | (Calm under pressure in codes)
HOSP-1097 | Rosa Nguyen | Pharmacy Technician | Pharmacy | certs:CPhT | Full-time | max:48 | pref:Flexible | OT:Yes | Active | Fri=D | Sat=O | Sun=O | next7d=24 | (Commutes far, dislikes back-to-backs)
HOSP-1098 | Carmen Müller | Registered Nurse | Pediatrics | certs:BLS, PALS | Full-time | max:48 | pref:Flexible | OT:Yes | Active | Fri=O | Sat=N | Sun=O | next7d=36 | (Quiet, dependable, rarely calls out)
HOSP-1099 | Oskar Wagner | Registered Nurse | General Medicine | certs:BLS | Part-time | max:30 | pref:Day | OT:Yes | Active | Fri=O | Sat=O | Sun=O | next7d=36 | (Union rep, watches hours closely)
HOSP-1100 | Mia Reyes | Registered Nurse | Oncology | certs:BLS, OCN | Full-time | max:48 | pref:Day | OT:Yes | On Leave | Fri=O | Sat=O | Sun=O | next7d=0 | (Calm under pressure in codes)`;
